import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  escapeSqlString,
  parseApprovedCsv,
  type ApprovedCsvRow,
} from "./places-csv";

const INPUT_PATH = resolve(process.cwd(), "tmp/google-place-approved-update.csv");
const UPDATE_SQL_PATH = resolve(process.cwd(), "tmp/google-place-update.sql");
const ROLLBACK_SQL_PATH = resolve(process.cwd(), "tmp/google-place-rollback.sql");
const BACKUP_TABLE = "public.shops_google_place_id_backup_20260712";
const TEMP_TABLE = "tmp_google_place_updates";
const EXPECTED_ROW_COUNT = 81;
const EXPECTED_TOTAL_LINKED = 82;

function buildInsertValues(rows: ApprovedCsvRow[]): string {
  return rows
    .map((row) => {
      const shopId = Number(row.shopId);
      if (!Number.isInteger(shopId) || shopId <= 0) {
        throw new Error(`不正なshopId: ${row.shopId}`);
      }

      const shopName = row.shopName.trim();
      const placeId = row.google_place_id.trim();

      if (!shopName || !placeId) {
        throw new Error(`shopId ${row.shopId} に空の必須項目があります。`);
      }

      return `  (${shopId}, '${escapeSqlString(shopName)}', '${escapeSqlString(placeId)}')`;
    })
    .join(",\n");
}

function buildUpdateSql(rows: ApprovedCsvRow[]): string {
  const insertValues = buildInsertValues(rows);

  return `-- Generated by npm run places:update:sql
-- Do not run automatically. Review in Supabase SQL Editor first.

BEGIN;

-- 1) Backup table (fails if already exists)
CREATE TABLE ${BACKUP_TABLE} (
  id integer PRIMARY KEY,
  name text NOT NULL,
  google_place_id text
);

INSERT INTO ${BACKUP_TABLE} (id, name, google_place_id)
SELECT id, name, google_place_id
FROM public.shops;

-- 2) Load approved CSV rows into a temp table
CREATE TEMP TABLE ${TEMP_TABLE} (
  shop_id integer PRIMARY KEY NOT NULL,
  shop_name text NOT NULL,
  google_place_id text NOT NULL UNIQUE
) ON COMMIT PRESERVE ROWS;

INSERT INTO ${TEMP_TABLE} (shop_id, shop_name, google_place_id)
VALUES
${insertValues};

-- 3) Pre-update safety checks
DO $$
DECLARE
  v_count integer;
BEGIN
  SELECT COUNT(*) INTO v_count FROM ${TEMP_TABLE};
  IF v_count <> ${EXPECTED_ROW_COUNT} THEN
    RAISE EXCEPTION 'tmp_google_place_updates count is %, expected ${EXPECTED_ROW_COUNT}', v_count;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM ${TEMP_TABLE} u
    WHERE TRIM(u.google_place_id) = ''
  ) THEN
    RAISE EXCEPTION 'Empty google_place_id found in CSV data';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM ${TEMP_TABLE} u
    LEFT JOIN public.shops s ON s.id = u.shop_id
    WHERE s.id IS NULL
  ) THEN
    RAISE EXCEPTION 'shop_id not found in shops table';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM ${TEMP_TABLE} u
    JOIN public.shops s ON s.id = u.shop_id
    WHERE TRIM(s.name) <> TRIM(u.shop_name)
  ) THEN
    RAISE EXCEPTION 'shop_name mismatch between CSV and shops';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM ${TEMP_TABLE} u
    JOIN public.shops s ON s.id = u.shop_id
    WHERE s.google_place_id IS NOT NULL AND TRIM(s.google_place_id) <> ''
  ) THEN
    RAISE EXCEPTION 'target shop already has google_place_id set';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM ${TEMP_TABLE} u
    JOIN public.shops s
      ON s.google_place_id = u.google_place_id
     AND s.id <> u.shop_id
    WHERE s.google_place_id IS NOT NULL AND TRIM(s.google_place_id) <> ''
  ) THEN
    RAISE EXCEPTION 'google_place_id already used by another shop';
  END IF;
END $$;

-- 4) Update shops
UPDATE public.shops AS s
SET google_place_id = u.google_place_id
FROM ${TEMP_TABLE} AS u
WHERE s.id = u.shop_id;

-- 5) Post-update safety checks
DO $$
DECLARE
  v_matched integer;
  v_total_linked integer;
BEGIN
  SELECT COUNT(*) INTO v_matched
  FROM ${TEMP_TABLE} u
  JOIN public.shops s ON s.id = u.shop_id
  WHERE s.google_place_id = u.google_place_id;

  IF v_matched <> ${EXPECTED_ROW_COUNT} THEN
    RAISE EXCEPTION 'post-update match count is %, expected ${EXPECTED_ROW_COUNT}', v_matched;
  END IF;

  SELECT COUNT(*) INTO v_total_linked
  FROM public.shops
  WHERE google_place_id IS NOT NULL AND TRIM(google_place_id) <> '';

  IF v_total_linked <> ${EXPECTED_TOTAL_LINKED} THEN
    RAISE EXCEPTION 'total linked shops is %, expected ${EXPECTED_TOTAL_LINKED}', v_total_linked;
  END IF;
END $$;

COMMIT;

-- 6) Verification queries (after COMMIT)
SELECT COUNT(*) AS updated_count_expected_${EXPECTED_ROW_COUNT}
FROM ${TEMP_TABLE} u
JOIN public.shops s ON s.id = u.shop_id
WHERE s.google_place_id = u.google_place_id;

SELECT COUNT(*) AS total_linked_expected_${EXPECTED_TOTAL_LINKED}
FROM public.shops
WHERE google_place_id IS NOT NULL AND TRIM(google_place_id) <> '';

SELECT
  s.id,
  s.name,
  s.google_place_id
FROM public.shops s
JOIN ${TEMP_TABLE} u ON u.shop_id = s.id
ORDER BY s.id;
`;
}

function buildRollbackSql(): string {
  return `-- Generated by npm run places:update:sql
-- Restores google_place_id values from backup table.

BEGIN;

UPDATE public.shops AS s
SET google_place_id = b.google_place_id
FROM ${BACKUP_TABLE} AS b
WHERE s.id = b.id;

SELECT COUNT(*) AS restored_match_count
FROM public.shops s
JOIN ${BACKUP_TABLE} b ON b.id = s.id
WHERE COALESCE(s.google_place_id, '') = COALESCE(b.google_place_id, '');

SELECT
  s.id,
  s.name,
  s.google_place_id
FROM public.shops s
ORDER BY s.id;

COMMIT;
`;
}

function main(): void {
  let csvContent: string;
  try {
    csvContent = readFileSync(INPUT_PATH, "utf-8");
  } catch {
    throw new Error(`CSVが見つかりません: ${INPUT_PATH}`);
  }

  const rows = parseApprovedCsv(csvContent);
  if (rows.length !== EXPECTED_ROW_COUNT) {
    throw new Error(
      `CSVのデータ行数が ${EXPECTED_ROW_COUNT} 件ではありません（実際: ${rows.length} 件）。`,
    );
  }

  const updateSql = buildUpdateSql(rows);
  const rollbackSql = buildRollbackSql();

  mkdirSync(resolve(process.cwd(), "tmp"), { recursive: true });
  writeFileSync(UPDATE_SQL_PATH, updateSql, "utf-8");
  writeFileSync(ROLLBACK_SQL_PATH, rollbackSql, "utf-8");

  console.log(`入力CSV: ${INPUT_PATH}`);
  console.log(`CSVから読み込んだ件数: ${rows.length}`);
  console.log(`更新対象件数: ${rows.length}`);
  console.log(`生成: ${UPDATE_SQL_PATH}`);
  console.log(`生成: ${ROLLBACK_SQL_PATH}`);
  console.log("SQLをまだ実行していません。");
  console.log("更新SQLにはバックアップ、安全確認、ロールバック用SQLが含まれています。");
}

main();
